BEGIN TRY 
DECLARE @NUM INT , @MSG VARCHAR(200)
SET @NUM = 5/0
PRINT 'THIS IS OUTPUT'
END TRY

BEGIN CATCH
PRINT 'DONT TRY TO DIVIDE THE NUMBER BY ZERO'
SET @MSG = (SELECT ERROR_MESSAGE());
PRINT @MSG
END CATCH


CREATE TABLE TE(ID INT PRIMARY KEY);

 

BEGIN
BEGIN TRY
INSERT INTO TE(ID)VALUES(1);
INSERT INTO TE(ID)VALUES(1);
END TRY
BEGIN CATCH
PRINT('Same Value Cannot Be Entered');
THROW;
END CATCH;
END;

BEGIN TRY 

DECLARE @num INT , @msg varchar(200) 

SET @num = 5/0 

PRINT 'THIS is not Possible : Will Raise Divide by Zero Exception' 

END TRY 

  

BEGIN CATCH 

PRINT 'DONT YOU TRY DIVIDING A NO by ZERO' 

SELECT ERROR_NUMBER() AS Error__Number, ERROR_SEVERITY() AS Error__Severity, 

ERROR_STATE() AS ErrorState, ERROR_PROCEDURE() AS ErrorProcedure, ERROR_LINE() AS ErrorLine, 

ERROR_MESSAGE() AS ErrorMessage; 

  

END CATCH 

GO 