CREATE PROCEDURE JOINEDTABLE
as

SELECT * 
FROM AGENTS
INNER JOIN CUSTOMER ON 
AGENTS.AGENT_CODE= CUSTOMER.AGENT_CODE;

GO
EXEC JOINEDTABLE;

--passing parameter

CREATE PROCEDURE SELECT_AREA @WORKING_AREA CHAR(35)
AS
SELECT * FROM AGENTS WHERE WORKING_AREA = 'BANGALORE';
GO
EXEC SELECT_AREA @WORKING_AREA ='Bangalore';

--passing three parameters

CREATE PROCEDURE PASSING @WORKING_AREA CHAR(35), @COMMISSION DECIMAL, @COUNTRY VARCHAR(25) 
AS 
SELECT * FROM AGENTS WHERE WORKING_AREA = @WORKING_AREA OR COMMISSION=@COMMISSION OR COUNTRY= @COUNTRY;
GO
EXEC PASSING @WORKING_AREA ='Bangalore', @COMMISSION=0.15, @COUNTRY= 'NEW YORK';

